config/routes.rb
# == Route Map (Updated 2014-10-20 22:02)
#
#         Prefix Verb   URI Pattern                    Controller#Action
#     promotions GET    /promotions(.:format)          promotions#index
#                POST   /promotions(.:format)          promotions#create
#  new_promotion GET    /promotions/new(.:format)      promotions#new
# edit_promotion GET    /promotions/:id/edit(.:format) promotions#edit
#      promotion GET    /promotions/:id(.:format)      promotions#show
#                PATCH  /promotions/:id(.:format)      promotions#update
#                PUT    /promotions/:id(.:format)      promotions#update
#                DELETE /promotions/:id(.:format)      promotions#destroy
#       students GET    /students(.:format)            students#index
#                POST   /students(.:format)            students#create
#    new_student GET    /students/new(.:format)        students#new
#   edit_student GET    /students/:id/edit(.:format)   students#edit
#        student GET    /students/:id(.:format)        students#show
#                PATCH  /students/:id(.:format)        students#update
#                PUT    /students/:id(.:format)        students#update
#                DELETE /students/:id(.:format)        students#destroy
#           root GET    /                              promotions#index
#

Learn::Application.routes.draw do
  devise_for :students
  namespace :admin do
    resources :achievements, :events
    resources :achievement_notes, only: :update
    resources :courses do
      member do
        get :evaluations
      end
    end
    resources :students do
      post :sync_profile
    end
    resources :promotions do
      post :sync_courses
      member do
        get :evaluations
      end
    end
    root to: 'students#index'
  end
  resources :courses, only: :show do
    get :evaluate
    patch 'evaluate' => 'courses#update_evaluation'
    post 'evaluate' => 'courses#update_evaluation'
  end
  get 'me' => 'dashboard#me', as: :me
  patch 'me' => 'dashboard#update_me', as: :update_me
  get 'api/projects/:teach_project_id' => 'api/projects#show'
  get 'api/promotions/:year' => 'api/promotions#show'
  root 'dashboard#index'
end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  date        :date
#  description :text
#  created_at  :datetime
#  updated_at  :datetime
#  course_id   :integer
#

class Event < ApplicationRecord
  belongs_to :course
  has_and_belongs_to_many :promotions
  has_and_belongs_to_many :teachers, class_name: 'Student'

  default_scope { order(:date) }

  def past?
    date < Date.today
  end

  def to_s
    "#{name}"
  end
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  
  respond_to :html

  def index
    @events = Event.all
    respond_with(@events)
  end

  def show
    respond_with(@event)
  end

  def new
    @event = Event.new
    respond_with(@event)
  end

  def edit
  end

  def create
    @event = Event.new(event_params)
    @event.save
    respond_with :admin, @event
  end

  def update
    @event.update(event_params)
    respond_with :admin, @event
  end

  def destroy
    @event.destroy
    respond_with :admin, @event
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:name, :date, :description, promotion_ids: [], teacher_ids: [])
    end
end

app/views/admin/events/_form.html.erb
<%= simple_form_for [:admin, @event] do |f| %>
  <%= f.error_notification %>
  <div class="row">
    <div class="col-md-4">
      <%= f.input :name, label: 'Nom' %>
      <%= f.input :date, html5: true %>
      <%= f.input :description %>
    </div>
    <div class="col-md-4">
      <%= f.association :promotions, as: :check_boxes %>
    </div>
    <div class="col-md-4">
      <%= f.association :teachers, as: :check_boxes, collection: Student.admin, label: 'Enseignants' %>
    </div>
  </div>
  <%= f.button :submit, 'Enregistrer' %>
<% end %>

app/views/admin/events/edit.html.erb
<%= title "#{@event} - Modifier" %>
<%= link_to 'Voir', [:admin, @event], class: 'btn btn-primary' %>
<%= render 'form' %>

app/views/admin/events/index.html.erb
<%= title 'Événements' %>
<%= link_to 'Nouvel événement', new_admin_event_path, class: 'btn btn-primary' %>
<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Date</th>
        <th>Description</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @events.each do |event| %>
        <tr>
          <td><%= link_to event, [:admin, event] %></td>
          <td><%= event.date %></td>
          <td><%= event.description %></td>
          <td>
            <%= link_to 'Edit', edit_admin_event_path(event), class: 'btn btn-primary btn-sm' %>
            <%= link_to 'Destroy', [:admin, event], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/events/new.html.erb
<%= title 'Nouvel événement' %>
<%= render 'form' %>

app/views/admin/events/show.html.erb
<%= title @event %>
<%= link_to 'Modifier', edit_admin_event_path(@event), class: 'btn btn-primary' %>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @event.date %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<h2>Promotions</h2>
<ul>
  <% @event.promotions.each do |promotion| %>
    <li><%= link_to promotion, [:admin, promotion] %></li>
  <% end %>
</ul>

<h2>Teachers</h2>
<ul>
  <% @event.teachers.each do |teacher| %>
    <li><%= link_to teacher, [:admin, teacher] %></li>
  <% end %>
</ul>