config/routes.rb
# == Route Map (Updated 2014-10-20 22:02)
#
#         Prefix Verb   URI Pattern                    Controller#Action
#     promotions GET    /promotions(.:format)          promotions#index
#                POST   /promotions(.:format)          promotions#create
#  new_promotion GET    /promotions/new(.:format)      promotions#new
# edit_promotion GET    /promotions/:id/edit(.:format) promotions#edit
#      promotion GET    /promotions/:id(.:format)      promotions#show
#                PATCH  /promotions/:id(.:format)      promotions#update
#                PUT    /promotions/:id(.:format)      promotions#update
#                DELETE /promotions/:id(.:format)      promotions#destroy
#       students GET    /students(.:format)            students#index
#                POST   /students(.:format)            students#create
#    new_student GET    /students/new(.:format)        students#new
#   edit_student GET    /students/:id/edit(.:format)   students#edit
#        student GET    /students/:id(.:format)        students#show
#                PATCH  /students/:id(.:format)        students#update
#                PUT    /students/:id(.:format)        students#update
#                DELETE /students/:id(.:format)        students#destroy
#           root GET    /                              promotions#index
#

Learn::Application.routes.draw do
  devise_for :students
  namespace :admin do
    resources :achievements, :events
    resources :achievement_notes, only: :update
    resources :courses do
      member do
        get :evaluations
      end
    end
    resources :students do
      post :sync_profile
    end
    resources :promotions do
      post :sync_courses
      member do
        get :evaluations
      end
    end
    root to: 'students#index'
  end
  resources :courses, only: :show do
    get :evaluate
    patch 'evaluate' => 'courses#update_evaluation'
    post 'evaluate' => 'courses#update_evaluation'
  end
  get 'me' => 'dashboard#me', as: :me
  patch 'me' => 'dashboard#update_me', as: :update_me
  get 'api/projects/:teach_project_id' => 'api/projects#show'
  get 'api/promotions/:year' => 'api/promotions#show'
  root 'dashboard#index'
end

app/models/achievement.rb
# == Schema Information
#
# Table name: achievements
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  text       :text
#  position   :integer
#  points     :integer
#  identifier :string(255)
#  why        :text
#  how        :text
#  created_at :datetime
#  updated_at :datetime
#  course_id  :integer
#  kind       :string
#

class Achievement < ApplicationRecord

  KIND_NOTE = 'note'
  KIND_GITHUB = 'github'
  KIND_HEROKU = 'heroku'
  KIND_CODECADEMY = 'codecademy'
  KIND_PLURALSIGHT = 'pluralsight'
  KINDS = [KIND_NOTE, KIND_GITHUB, KIND_HEROKU, KIND_CODECADEMY, KIND_PLURALSIGHT]

  has_many :notes
  belongs_to :course

  default_scope { order(:position) }

  def kind_note?
    kind == Achievement::KIND_NOTE
  end

  def done_by?(student)
    points_earned_by(student) > 0
  end

  def points_earned_by(student)
    case kind
    when KIND_NOTE
      note_for_student(student).value
    else
      if student.respond_to? identifier_command
        achievement_validated = student.send(identifier_command, identifier_title)
        achievement_validated ? points : 0
      else
        0
      end
    end
  end

  def note_for_student(student)
    notes.where(student: student).first_or_create
  end

  def to_s
    "#{title}"
  end

  protected

  def identifier_command
    "#{identifier_service}_validated?"
  end

  def identifier_service
    identifier.split('://').first
  end

  def identifier_title
    identifier.split('://').last
  end

end

app/models/achievement/note.rb
# == Schema Information
#
# Table name: achievement_notes
#
#  id             :bigint(8)        not null, primary key
#  achievement_id :bigint(8)
#  student_id     :bigint(8)
#  value          :float            default(0.0)
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Achievement::Note < ApplicationRecord
  belongs_to :achievement
  belongs_to :student
end

app/controllers/admin/achievements_controller.rb
class Admin::AchievementsController < Admin::ApplicationController
  before_action :set_achievement, only: [:show, :edit, :update, :destroy]

  respond_to :html

  add_breadcrumb 'Projets', :admin_courses_path

  def index
    @achievements = Achievement.all
  end

  def show
    add_breadcrumb @achievement.course, [:admin, @achievement.course]
    add_breadcrumb @achievement
  end

  def new
    @achievement = Achievement.new
  end

  def edit
    add_breadcrumb @achievement.course, [:admin, @achievement.course]
    add_breadcrumb @achievement, [:admin, @achievement]
    add_breadcrumb 'Modifier'
  end

  def create
    @achievement = Achievement.create achievement_params
    respond_with :admin, @achievement.course
  end

  def update
    @achievement.update achievement_params
    respond_with :admin, @achievement.course
  end

  def destroy
    @achievement.destroy
    respond_with :admin, @achievement
  end

  private

  def set_achievement
    @achievement = Achievement.find(params[:id])
  end

  def achievement_params
    params.require(:achievement).permit(:title, :text, :position, :points, :identifier, :why, :how, :kind, :course_id)
  end
end

app/views/admin/achievements/_form.html.erb
<%= simple_form_for [:admin, @achievement] do |f| %>
  <%= f.error_notification %>
  <%= f.association :course, label_method: :name_with_promotion %>
  <%= f.input :title %>
  <%= f.input :text %>
  <%= f.input :position %>
  <%= f.input :points %>
  <%= f.input :kind, collection: Achievement::KINDS, include_blank: false %>
  <%= f.input :identifier %>
  <%= f.input :why %>
  <%= f.input :how %>
  <%= f.button :submit, 'Enregistrer' %>
<% end %>

app/views/admin/achievements/edit.html.erb
<%= title "#{@achievement} - Modifier" %>
<%= link_to 'Voir', [:admin, @achievement], class: 'btn btn-primary' %>
<%= render 'form' %>

app/views/admin/achievements/index.html.erb
<%= title 'Réalisations' %>
<%= link_to 'Nouvelle réalisation', new_admin_achievement_path, class: 'btn btn-primary' %>
<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Course</th>
        <th>Title</th>
        <th>Kind</th>
        <th>Identifier</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @achievements.each do |achievement| %>
        <tr>
          <td><%= link_to achievement.course, [:admin, achievement.course] if achievement.course %></td>
          <td><%= link_to achievement.title, [:admin, achievement] %></td>
          <td><%= achievement.kind %></td>
          <td><%= achievement.identifier %></td>
          <td>
            <%= link_to 'Edit', edit_admin_achievement_path(achievement), class: 'btn btn-primary btn-sm' if current_student.admin %>
            <%= link_to 'Destroy', [:admin, achievement], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/achievements/new.html.erb
<%= title 'Nouvelle réalisation' %>
<%= render 'form' %>

app/views/admin/achievements/show.html.erb
<%= title @achievement %>
<%= link_to 'Modifier', edit_admin_achievement_path(@achievement), class: 'btn btn-primary' if current_student.admin %>
<p><%= @achievement.text %></p>
<h2>Pourquoi ?</h2>
<p><%= simple_format@achievement.why %></p>
<h2>Comment ?</h2>
<p><%= simple_format @achievement.how %></p>