config/routes.rb
# == Route Map (Updated 2014-10-20 22:02)
#
#         Prefix Verb   URI Pattern                    Controller#Action
#     promotions GET    /promotions(.:format)          promotions#index
#                POST   /promotions(.:format)          promotions#create
#  new_promotion GET    /promotions/new(.:format)      promotions#new
# edit_promotion GET    /promotions/:id/edit(.:format) promotions#edit
#      promotion GET    /promotions/:id(.:format)      promotions#show
#                PATCH  /promotions/:id(.:format)      promotions#update
#                PUT    /promotions/:id(.:format)      promotions#update
#                DELETE /promotions/:id(.:format)      promotions#destroy
#       students GET    /students(.:format)            students#index
#                POST   /students(.:format)            students#create
#    new_student GET    /students/new(.:format)        students#new
#   edit_student GET    /students/:id/edit(.:format)   students#edit
#        student GET    /students/:id(.:format)        students#show
#                PATCH  /students/:id(.:format)        students#update
#                PUT    /students/:id(.:format)        students#update
#                DELETE /students/:id(.:format)        students#destroy
#           root GET    /                              promotions#index
#

Learn::Application.routes.draw do
  devise_for :students
  namespace :admin do
    resources :achievements, :events
    resources :achievement_notes, only: :update
    resources :courses do
      member do
        get :evaluations
      end
    end
    resources :students do
      post :sync_profile
    end
    resources :promotions do
      post :sync_courses
      member do
        get :evaluations
      end
    end
    root to: 'students#index'
  end
  resources :courses, only: :show do
    get :evaluate
    patch 'evaluate' => 'courses#update_evaluation'
    post 'evaluate' => 'courses#update_evaluation'
  end
  get 'me' => 'dashboard#me', as: :me
  patch 'me' => 'dashboard#update_me', as: :update_me
  get 'api/projects/:teach_project_id' => 'api/projects#show'
  get 'api/promotions/:year' => 'api/promotions#show'
  root 'dashboard#index'
end

app/models/promotion.rb
# == Schema Information
#
# Table name: promotions
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#  year       :integer
#
require 'net/http'

class Promotion < ApplicationRecord
  has_many :students
  validates :name, presence: true
  has_and_belongs_to_many :events
  has_many :courses
  has_many :evaluations, through: :students

  default_scope { order :name }

  include Codeschool
  include Codecademy

  def students_csv
  end

  def students_csv=(value)
    require 'csv'
    value = value.gsub(';', ',')
    CSV.parse(value).each do |row|
      student = Student.where(email: row[2]).first_or_create
      student.firstname = row[0]
      student.lastname = row[1]
      student.password = row[3]
      student.promotion_id = id
      student.save
    end
  end

  def average_note
    students.average(:note)
  end

  def sync_courses!
    uri = URI teach_api_url
    response = Net::HTTP.get uri
    data = JSON.parse response
    data['projects'].each do |project|
      project_id = project['id'].to_i
      course = Course.where(teach_project_id: project_id, promotion_id: id).first_or_initialize
      course.name = project['label']
      course.description = project['description']
      course.starting_at = project['start_date']
      course.save
    end
  end

  def to_s
    "#{name}"
  end

  protected

  def teach_api_url
    "http://teach.mmibordeaux.com/api/promotions/#{year}"
  end
end

app/controllers/admin/promotions_controller.rb
class Admin::PromotionsController < Admin::ApplicationController
  before_action :set_promotion

  add_breadcrumb 'Promotions', :admin_promotions_path

  respond_to :html

  def index
    @promotions = Promotion.all
    @title = 'Promotions'
  end

  def show
    @title = @promotion.to_s
    add_breadcrumb @title
  end

  def new
    @promotion = Promotion.new
    @title = 'Nouvelle promotion'
    add_breadcrumb @title
  end

  def edit
    @title = "#{@promotion} - Modifier"
    add_breadcrumb @promotion, [:admin, @promotion]
    add_breadcrumb 'Modifier'
  end

  def sync_courses
    @promotion.sync_courses!
    redirect_to admin_promotion_path(@promotion)
  end

  def evaluations
    @title = 'Evaluations'
    add_breadcrumb @promotion, [:admin, @promotion]
    add_breadcrumb @title
  end

  def create
    @promotion = Promotion.create promotion_params
    respond_with :admin, @promotion
  end

  def update
    @promotion.update promotion_params
    respond_with :admin, @promotion
  end

  def destroy
    @promotion.destroy
    respond_with :admin, @promotion
  end

  private

  def set_promotion
    @promotion = Promotion.find(params[:id]) if params.include? :id
    @promotion = Promotion.find(params[:promotion_id]) if params.include? :promotion_id
  end

  def promotion_params
    params.require(:promotion).permit(:name, :year, :students_csv)
  end
end

app/controllers/api/promotions_controller.rb
class Api::PromotionsController < Api::ApplicationController
  def show
    @promotion = Promotion.find_by year: params[:year]
    @courses = @promotion.courses.done
  end
end

app/views/admin/promotions/_form.html.erb
<%= simple_form_for [:admin, @promotion] do |f| %>
  <%= f.error_notification %>
  <%= f.input :name %>
  <%= f.input :year %>
  <%= f.input :students_csv, as: :text, placeholder: 'Prénom;Nom;prenom.nom@mmibordeaux.com;Mot de passe' %>
  <%= f.button :submit, 'Enregistrer' %>
<% end %>

app/views/admin/promotions/edit.html.erb
<%= render 'form' %>

app/views/admin/promotions/evaluations.html.erb
<%= area_chart [
    :knowledge_acquired,
    :technical_skills_acquired,
    :soft_skills_acquired,
    :quality
  ].map { |key|
    {
      name: key.to_s.titleize,
      data: @promotion.courses.map { |course|
        [
          "##{course.teach_project_id} #{course.name}",
          course.send(key)
        ]
      }
    }
  },
  min: 0,
  legend: 'bottom',
  height: '600px',
  curve: false
%>

<h2 class="mt-5">Nombre d'évaluations (<%= @promotion.evaluations.count %> au total)</h2>
<%= column_chart @promotion.courses.map { |course|
    [
      "#{course.name} ##{course.teach_project_id}",
      course.evaluations.count
    ]
   }
%>

<h2 class="mt-5">Répartition par qualité</h2>

<div class="row">
  <% Course::QUALITY.each do |quality| %>
  <div class="col-md-2">
    <h5>
      <%= quality[:title] %>
      <span class="small">(<= <%= quality[:to].round %>)</span>
    </h5>
    <ul>
      <% Course.for_promotion_with_quality(@promotion, quality).each do |course| %>
        <li class="mb-2 small"><%= link_to course, evaluations_admin_course_path(course) %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
</div>

<h2 class="mt-5">Détails</h2>
<p class="small">Les évaluations sont présentées sur 10.</p>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Projet</th>
      <th>Evaluations</th>
      <th class="small">Qualité globale du projet</th>
      <th class="small">Connaissances acquises</th>
      <th class="small">Compétences techniques acquises</th>
      <th class="small">Compétences relationnelles acquises (soft skills)</th>
    </tr>
  </thead>
  <tbody>
    <% @promotion.courses.each do |course| %>
      <tr>
        <td><%= link_to course, evaluations_admin_course_path(course) %></td>
        <td><%= course.evaluations.count %></td>
        <td><%= course.quality %></td>
        <td><%= course.knowledge_acquired %></td>
        <td><%= course.technical_skills_acquired %></td>
        <td><%= course.soft_skills_acquired %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/promotions/index.html.erb
<%= link_to 'Nouvelle promotion',
            new_admin_promotion_path,
            class: 'btn btn-primary' %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Nom</th>
      <th>Etudiants</th>
      <th>Evaluations</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @promotions.each do |promotion| %>
      <tr>
        <td><%= promotion %></td>
        <td><%= promotion.students.count %></td>
        <td><%= promotion.evaluations.count %></td>
        <td class="text-end">
          <%= link_to 'Voir', [:admin, promotion], class: 'btn btn-primary btn-sm' %>
          <%= link_to 'Evaluations', evaluations_admin_promotion_path(promotion), class: 'btn btn-primary btn-sm' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/promotions/new.html.erb
<%= render 'form' %>

app/views/admin/promotions/show.html.erb
<%= link_to 'Modifier', edit_admin_promotion_path(@promotion), class: 'btn btn-primary' %>
<%= link_to 'Actualiser les profils des étudiants', '', class: 'btn btn-primary promotion-sync' %>
<%= link_to 'Synchroniser les cours avec Teach', admin_promotion_sync_courses_path(@promotion), method: :post, class: 'btn btn-primary' %>
<%= link_to 'Evaluations', evaluations_admin_promotion_path(@promotion), class: 'btn btn-primary' %>

<div class="row">
  <div class="col-md-6">
    <h2 class="mt-5">Etudiants</h2>
    <div class="table-responsive">
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th></th>
            <th>Etudiant</th>
            <!--
            <th class="small">Codecademy</th>
            <th class="small">Github</th>
            <th class="small">Github repo</th>
            <th class="small">Heroku app</th>
            -->
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @promotion.students.each do |student| %>
            <tr>
              <td><%= link_to fa_icon('refresh'), admin_student_sync_profile_path(student), class: 'sync' %></td>
              <td><%= student %></td>
              <!--
              <td class="small"><%= link_to student.codecademy, student.codecademy_url, target: '_blank' unless student.codecademy_url.nil? %></td>
              <td class="small"><%= link_to student.github_identifier, student.github_identifier_url, target: '_blank' unless student.github_identifier_url.nil? %></td>
              <td class="small"><%= link_to student.github_repository, student.github_repository_url, target: '_blank' unless student.github_repository_url.nil? %></td>
              <td class="small"><%= link_to student.heroku_app, student.heroku_app_url, target: '_blank' unless student.heroku_app_url.nil? %></td>
              -->
              <td class="text-end">
                <%= link_to 'Voir', admin_student_path(student), class: 'btn btn-primary btn-sm' %>
                <%= link_to 'Modifier', edit_admin_student_path(student), class: 'btn btn-primary btn-sm' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="col-md-6">
    <h2 class="mt-5">Projets</h2>
    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Début</th>
            <th>Projet</th>
            <th>Evaluations</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @promotion.courses.each do |course| %>
            <tr class="<%= 'done' if course.done? %><%= 'current' if course.current? %>">
              <td><%= course.starting_at.strftime '%d/%m/%Y' %></td>
              <td><%= course %></td>
              <td><%= course.evaluations.count %></td>
              <td class="text-end"><%= link_to 'Voir', [:admin, course], class: 'btn btn-primary btn-sm' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>