config/routes.rb
# == Route Map (Updated 2014-10-20 22:02)
#
#         Prefix Verb   URI Pattern                    Controller#Action
#     promotions GET    /promotions(.:format)          promotions#index
#                POST   /promotions(.:format)          promotions#create
#  new_promotion GET    /promotions/new(.:format)      promotions#new
# edit_promotion GET    /promotions/:id/edit(.:format) promotions#edit
#      promotion GET    /promotions/:id(.:format)      promotions#show
#                PATCH  /promotions/:id(.:format)      promotions#update
#                PUT    /promotions/:id(.:format)      promotions#update
#                DELETE /promotions/:id(.:format)      promotions#destroy
#       students GET    /students(.:format)            students#index
#                POST   /students(.:format)            students#create
#    new_student GET    /students/new(.:format)        students#new
#   edit_student GET    /students/:id/edit(.:format)   students#edit
#        student GET    /students/:id(.:format)        students#show
#                PATCH  /students/:id(.:format)        students#update
#                PUT    /students/:id(.:format)        students#update
#                DELETE /students/:id(.:format)        students#destroy
#           root GET    /                              promotions#index
#

Learn::Application.routes.draw do
  devise_for :students
  namespace :admin do
    resources :achievements, :events
    resources :achievement_notes, only: :update
    resources :courses do
      member do
        get :evaluations
      end
    end
    resources :students do
      post :sync_profile
    end
    resources :promotions do
      post :sync_courses
      member do
        get :evaluations
      end
    end
    root to: 'students#index'
  end
  resources :courses, only: :show do
    get :evaluate
    patch 'evaluate' => 'courses#update_evaluation'
    post 'evaluate' => 'courses#update_evaluation'
  end
  get 'me' => 'dashboard#me', as: :me
  patch 'me' => 'dashboard#update_me', as: :update_me
  get 'api/projects/:teach_project_id' => 'api/projects#show'
  get 'api/promotions/:year' => 'api/promotions#show'
  root 'dashboard#index'
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
  before_action :admin_only

  add_breadcrumb 'Admin'

  def admin_only
    raise ActionController::RoutingError, 'Forbidden' unless current_student.admin
  end
end

app/controllers/api/application_controller.rb
class Api::ApplicationController < ApplicationController
  skip_before_action :authenticate_student!
  before_action :set_default_response_format

  protected
  
  def set_default_response_format
    request.format = :json
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_student!
  before_action :configure_permitted_parameters, if: :devise_controller?

  add_breadcrumb 'Learn', :root_path

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:firstname, :lastname, :promotion_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def line(*args)
    raw "<tr>#{args.map { |arg| "<td>#{arg}</td>" }.join('')}</tr>"
  end

  def title(value=nil)
    content_for :title, value
    raw "<h1>#{value}</h1>"
  end
end

app/views/application/_breadcrumb.html.erb
<ol class="breadcrumb">
  <%= render_breadcrumbs separator: '&nbsp;/&nbsp;' %>
</ol>

app/views/application/_footer.html.erb
<footer>
  <div class="inner">
    <div class="logo logo-black">
      <%= image_tag 'mmi-bordeaux.png' %>
      <p>Learn</p>
    </div>
    <p class="version">
      <strong>Version 2.5</strong><br/>
      Hogwarts Legacy
    </p>
    <% if current_student %>
      <%= link_to 'Déconnexion',
                  destroy_student_session_path,
                  method: :delete,
                  class: 'btn btn-light btn-sm' %>
    <% end %>
  </div>
</footer>

app/views/application/_jumbotron.html.erb
<div class="jumbotron <%= controller_name %>">
  <div>
    <h1><%= raw @title %></h1>
    <% if @subtitle.present? %><p><%= simple_format @subtitle %></p><% end %>
  </div>
</div>

app/views/application/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-transparent">
  <div class="container-fluid">
    <%= link_to root_path, class:'navbar-brand logo' do %>
      <%= image_tag 'mmi-bordeaux.png' %>
      <p>Learn</p>
    <% end %>
    <button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto">
        <% if student_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Accueil', root_path, class: 'nav-link' %>
          </li>
          <% if current_student.admin %>
            <li class="nav-item dropdown">
              <a  class="nav-link dropdown-toggle"
                  href="#"
                  id="navbarDropdown"
                  role="button"
                  data-bs-toggle="dropdown"
                  aria-expanded="false">
                Admin
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to 'Etudiants', admin_students_path, class: 'dropdown-item' %>
                <%= link_to 'Promotions', admin_promotions_path, class: 'dropdown-item' %>
                <%= link_to 'Projets', admin_courses_path, class: 'dropdown-item' %>
                <%= link_to 'Réalisations', admin_achievements_path, class: 'dropdown-item' %>
                <%= link_to 'Evénements', admin_events_path, class: 'dropdown-item' %>
              </ul>
            </li>
          <% end %>
          <li class="nav-item">
            <%= link_to 'Mon profil', me_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/application/_notice.html.erb
<% unless notice.nil? %>
  <p class="alert alert-success">
    <a href="#" class="close" data-bs-dismiss="alert" aria-label="close">&times;</a>
    <%= notice %>
  </p>
<% end %>
<% unless alert.nil? %>
  <p class="alert alert-warning">
    <a href="#" class="close" data-bs-dismiss="alert" aria-label="close">&times;</a>
    <%= alert %>
  </p>
<% end %>